### ISSUE TITLE
Crashing functions in `matrix_stack` 's implementation

### ISSUE THREAD

**Issue by QwarksDev** [drohmer/cgp#1]
Noticed a bug in [+=operator](https://github.com/drohmer/CGP/blob/8fd65ec9d302a68b6e2b93e702ce3d64e26e150f/library/cgp/core/containers/matrix_stack/matrix_stack.hpp#L637), [-=operator](https://github.com/drohmer/CGP/blob/8fd65ec9d302a68b6e2b93e702ce3d64e26e150f/library/cgp/core/containers/matrix_stack/matrix_stack.hpp#L641) and maybe [/=operator](https://github.com/drohmer/CGP/blob/8fd65ec9d302a68b6e2b93e702ce3d64e26e150f/library/cgp/core/containers/matrix_stack/matrix_stack.hpp#L705).

Found by compiling this code:
```cpp
mat3 c = mat3();
c -= my_matrix_computation(val);
```
I got this error message:
```
{project_path}/cgp/library/cgp/core/containers/matrix_stack/matrix_stack.hpp: In instantiation of ‘cgp::matrix_stack<T, N1, N2>& cgp::operator-=(matrix_stack<T, N1, N2>&, const matrix_stack<T, N1, N2>&) [with T = float; int N1 = 3; int N2 = 3]’:
{project_path}/cgp/library/cgp/core/containers/matrix_stack/matrix_stack.hpp:638:5: warning: no return statement in function returning non-void [-Wreturn-type]   
```
And an instant black screen into app crash.

Fixed it by adding:
```cpp
return a;
```
At the end of the previously stated cgp functions.

**Comment by drohmer** [comment]
True thanks, the code should be corrected.

**Comment by QwarksDev** [comment]
By the way, shouldn't [this line](https://github.com/drohmer/CGP/blob/bb6dd43ca9a9a4c8aa2f2d365e162f37393731c2/library/cgp/core/containers/matrix_stack/matrix_stack.hpp#L637) be
```cpp
a.data -= b.data
```
as we are in the `operator-=` override?

**Comment by drohmer** [comment]
Of course, yes, thanks !
